const iconRegistry = {
  'add-circle': { path: 'assets/icons/light/add-circle-1.svg', alt: 'Add Circle' },
  'alarm-bell': { path: 'assets/icons/light/alarm-bell-ring.svg', alt: 'Alarm Bell' },
  'alert-triangle': { path: 'assets/icons/light/alert-triangle.svg', alt: 'Alert Triangle' },
  'alert-circle': { path: 'assets/icons/light/alert-circle.svg', alt: 'Alert Circle' },
  'app-window-text': { path: 'assets/icons/light/app-window-text.svg', alt: 'App Window' },
  'arrow-down': { path: 'assets/icons/light/arrow-button-down-2.svg', alt: 'Arrow Down' },
  'arrow-left': { path: 'assets/icons/light/arrow-left-1.svg', alt: 'Arrow left' },
  'arrow-right': { path: 'assets/icons/light/arrow-right-1.svg', alt: 'Arrow right' },
  'arrow-thick-left': { path: 'assets/icons/light/arrow-thick-left.svg', alt: 'Arrow Back' },
  'arrow-thick-up': { path: 'assets/icons/light/arrow-thick-up.svg', alt: 'Arrow Up' },
  'arrow-thick-down': { path: 'assets/icons/light/arrow-thick-down.svg', alt: 'Arrow Down' },
  'arrow-up': { path: 'assets/icons/light/arrow-button-up-2.svg', alt: 'Arrow Up' },
  'book-open': { path: 'assets/icons/light/book-open.svg', alt: 'Book Open' },
  'browser-gauge': {  path: '/assets/icons/light/browser-gauge.svg', alt: 'Browser Gauge' },
  card: { path: 'assets/icons/light/card-game-diamond.svg', alt: 'Card' },
  'check-circle': { path: 'assets/icons/light/check-circle-1.svg', alt: 'Check Circle' },
  clear: { path: 'assets/icons/light/layers-grid-disable.svg', alt: 'Clear' },
  close: { path: 'assets/icons/light/close.svg', alt: 'close' },
  'cloud-monitor-upload': { path: '/assets/icons/light/cloud-monitor-upload.svg', alt: 'Cloud Monitor Upload' },
  'database-connect': {  path: '/assets/icons/light/database-connect.svg', alt: 'Database connect' },
  deck: { path: 'assets/icons/light/card-game-cards.svg', alt: 'Deck' },
  'dot-menu': { path: '/assets/icons/light/navigation-menu-horizontal.svg', alt: 'Dot menu' },
  expand: { path: 'assets/icons/light/move-expand-vertical.svg', alt: 'Expand' },
  export: { path: 'assets/icons/light/arrow-thick-circle-up-1.svg', alt: 'export' },
  filter: { path: 'assets/icons/light/filter-1.svg', alt: 'Filter' },
  'floppy-disk': { path: 'assets/icons/light/floppy-disk-2.svg', alt: 'Floppy Disk' },
  hierarchy: { path: 'assets/icons/light/hierarchy-6.svg', alt: 'Hierarchy' },
  'keyboard-right': { path: 'assets/icons/light/keyboard-arrow-right.svg', alt: 'Arrow right' },
  label: { path: '/assets/icons/light/tags.svg', alt: 'Label' },
  layout: { path: 'assets/icons/light/layout.svg', alt: 'Layout' },
  'login-key': { path: '/assets/icons/light/login-key-1.svg', alt: 'Login Key' },
  logo: { path: 'assets/icons/logo/rocket-turtle-hawkes-blue.svg', alt: 'Cumulus' },
  menu: { path: 'assets/icons/light/navigation-menu.svg', alt: 'Menu' },
  monitor: { path: 'assets/icons/light/monitor.svg', alt: 'Monitor' },
  'monitor-beat': { path: 'assets/icons/light/monitor-heart-beat.svg', alt: 'Monitor Heart' },
  'monitor-rate': { path: 'assets/icons/light/monitor-heart-rate.svg', alt: 'Monitor Rate' },
  'navigation-menu-vertical': { path: '/assets/icons/light/navigation-menu-vertical.svg', alt: 'Navigation menu vertical' },
  'pin-multiple': { path: '/assets/icons/light/trip-pin-multiple.svg', alt: 'Multiple pins' },
  page: { path: 'assets/icons/light/notes-paper.svg', alt: 'Page' },
  remove: { path: 'assets/icons/light/subtract-circle.svg', alt: 'Remove' },
  reorder: { path: 'assets/icons/light/reorder.svg', alt: 'Reorder' },
  search: { path: 'assets/icons/light/search.svg', alt: 'Search' },
  server: { path: 'assets/icons/light/server-3.svg', alt: 'Server' },
  settings: { path: 'assets/icons/light/cog-1.svg', alt: 'Settings' },
  share: { path: 'assets/icons/light/share.svg', alt: 'Share' },
  shrink: { path: 'assets/icons/light/move-shrink-vertical.svg', alt: 'Shrink' },
  'signal-loading': { path: 'assets/icons/light/signal-loading.svg', alt: 'Signal Loading' },
  'sort-asc': { path: 'assets/icons/light/arrange-letter.svg', alt: 'Sort Asc' },
  'sort-desc': { path: 'assets/icons/light/arrange-letter-desc.svg', alt: 'Sort Desc' },
  stopwatch: { path: '/assets/icons/light/time-stopwatch.svg', alt: 'Stopwatch' },
  sync: { path: 'assets/icons/light/synchronize-arrow-clock.svg', alt: 'Sync' },
  'synchronize-arrows': { path: 'assets/icons/light/synchronize-arrows-1.svg', alt: 'Synchronize Arrows' },
  'user-profile': { path: 'assets/icons/light/single-man-circle.svg', alt: 'User Profile' },
  view: { path: 'assets/icons/light/view-1.svg', alt: 'View' },
  workspaces: { path: 'assets/icons/light/synchronize-arrow-clock.svg', alt: 'Workspaces' },
};

export default iconRegistry;
